using namespace System.Net

# $sub and $DID are injected by CloudLabs. JIT is learner-created Defender state.
$rg=(Get-AzResource -ErrorAction SilentlyContinue | Where-Object { $_.Name -like 'asclab*' } | Select-Object -First 1).ResourceGroupName; if(-not $rg){ throw 'Could not locate the lab resource group: no resource named asclab* found in the subscription.' };$count=0;$found=$false;$failure='JIT validation has not run.'
function V($o,$n){if($null-eq $o){return $null};$p=$o.PSObject.Properties[$n];if($null-eq $p){return $null};$p.Value}
function Reply($s,$m){if($s-eq 'Succeeded'){$body=@{Status = "Succeeded";Message = $m}|ConvertTo-Json -Compress}else{$body=@{Status = "Failed";Message = $m}|ConvertTo-Json -Compress};Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{StatusCode=[HttpStatusCode]::OK;Body=$body}) -Clobber}
function Any($p){$x=V $p 'AllowedSourceAddressPrefix';if($null-ne $x -and [string]$x-in @('*','Any')){return $true};$x=V $p 'AllowedSourceAddressPrefixes';if($null-ne $x){$a=@($x|ForEach-Object{[string]$_});return $a.Count-eq 1 -and $a[0]-in @('*','Any')};return $false}
function VM($v,$n){$m=@($v|Where-Object{[string](V $_ 'Id')-match "/virtualMachines/$([regex]::Escape($n))$"});if($m.Count-ne 1){throw "Expected exactly one JIT VM entry for '$n'; found $($m.Count)."};$m[0]}
do{$count++;try{Set-AzContext -Subscription $sub -ErrorAction Stop|Out-Null;$p=@(Get-AzJitNetworkAccessPolicy -ResourceGroupName $rg -Location eastus -Name default -ErrorAction Stop);if($p.Count-ne 1){throw "Expected exactly one JIT policy in '$rg'."};$v=V $p[0] 'VirtualMachines';$w=VM @($v) asclab-win;$l=VM @($v) asclab-linux;$wp=@(V $w 'Ports');$lp=@(V $l 'Ports');if($wp.Count-ne 1 -or [int](V $wp[0] 'Number')-ne 3389){throw 'asclab-win must have port 3389.'};if($lp.Count-ne 1 -or [int](V $lp[0] 'Number')-ne 22){throw 'asclab-linux must have port 22.'};if([string](V $wp[0] 'MaxRequestAccessDuration')-ne 'PT3H' -or [string](V $lp[0] 'MaxRequestAccessDuration')-ne 'PT3H'){throw 'Both JIT rules must use PT3H.'};if(-not(Any $wp[0])-or -not(Any $lp[0])){throw 'Both JIT rules must allow source Any.'};$found=$true;Reply 'Succeeded' "JIT policy in '$rg' contains ports 3389 and 22 with PT3H and source Any."}catch{$failure=$_.Exception.Message;Reply 'Failed' "JIT validation attempt $count of 3 failed: $failure";if($count-lt 3){Start-Sleep -Seconds 10}}}while($count-lt 3 -and -not $found)
if(-not $found){Reply 'Failed' "JIT validation failed after 3 attempts in '$rg'. Last error: $failure"}